name: gatorexchange

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Go Development Environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      
      - name: Setting up Node.js Development Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
      
      - name: Building GatorExchange Backend
        run: |
          cd backend
          go build main.go
          
      - name: Building GatorExchange Frontend
        run: |
          cd front-end
          npm install
          npm run build
  
  testing:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v2
        - name: Test GatorExchange Backend
          env:
            ENV_FILE: ${{ secrets.ENV_FILE }}
          run: |
            cd backend/tests
            echo "$ENV_FILE" >> .env
            cd ..
            go test ./tests/...
