name: gatorexchange

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Go Development Environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Building GatorExchange Backend
        run: |
          cd backend
          go build main.go
